### PR TITLE
Fixed case mismatch for some paths.

### PR DESCRIPTION
**Pull request by cookiemon**
Paths on Linux are case sensitive. Should not break other platforms.

### CODE REVIEW

**Comment by vgturtle127** [comment]
@adelikat @zeromus @cookiemon Can this be closed? Or is it needing a rebase and testing? I know we have the mono branch, but is this patch still relevant?

**Comment by zeromus** [comment]
it's for @Sappharad to evaluate

**Comment by Sappharad** [comment]
Sorry, I didn't realize. 
I can check it out tonight.

**Comment by Sappharad** [comment]
Done.

**Pull request closed without merging**
