### PR TITLE
Create LuaPictureBox class and implement it

### PR DESCRIPTION
**Pull request by Trivial-Man**
This code factors all the drawing methods used in LuaCanvas into it's own new component class: LuaPictureBox. This new class is then implemented as a component that can be added to forms.

This makes it possible to create forms that have buttons and text fields and other such forms of interactivity, and also that are capable of displaying information graphically. They become slightly more robust, if more complex, canvases themselves. LuaCanvas remains functionally identical to what it was previously.

This pull request also implements the changes in @TASEditor's PR, and adds in the error messages for when DrawImage and similar methods are called but a file isn't found.

### CODE REVIEW

**Comment by Trivial-Man** [comment]
Whoa, hold on. Something funny happened here

**Comment by adelikat** [comment]
I did some refactoring that may affect this PR.  Can you resolve it with current master?
Let me know, and then I will pull this

**Comment by Trivial-Man** [comment]
I've got most of this resolved, but I'm having a small issue that seems related to #908. I am able to rename any of the Forms functions by changing the name used in LuaMethod. However, no matter what I name the functions in LuaCanvas the name that calls them is the C# method name. Otherwise things seem to work. I'll upload what I have in a few hours.

**Comment by zeromus** [comment]
Oops, I guess i should have let you do that

**Comment by Trivial-Man** [comment]
Sorry that took 4 commits for what should have been 1, but everything should be in there and working now. Let me know if there are issues.
You can test most of the drawing functions with some simple scripts here:
https://github.com/Trivial-Man/LuaDrawingExamples

**Pull request merged**
