### PR TITLE
Canvas drawing

### PR DESCRIPTION
**Pull request by TASeditor**
TODO: implement DrawBezier and DrawPolygon, DrawImage doesn't draw

### CODE REVIEW

**Comment by vgturtle127** [comment]
10/10 would pie again.

**Comment by zeromus** [comment]
sorry TASeditor, someone else made a PR for this. I had to choose one to merge, and I chose the other one because I forgot yours was here. Can you please evaluate it for your purposes?

**Comment by TASeditor** [comment]
DrawImage still doesn't draw it to the canvas. Everything else works.
Mine has DrawArc function, which is missing in the other one.

**Comment by zeromus** [comment]
Oh. weird. OK, well, let's get this synchronized and then you two can sort it out amongst yourselves

**Pull request closed without merging**
