### PR TITLE
Add linux version of LibretroBridge

### PR DESCRIPTION
**Pull request by Morilli**
Have tested in wsl2 and has generally worked 🤷‍♀️

### CODE REVIEW

**Comment by YoshiRulz** [comment]
I wasn't able to load SM64. (Though the libretro core may be at fault, I haven't checked.)

Tail of `MONO_LOG_LEVEL=debug MONO_LOG_MASK=dll ./EmuHawkMono.sh` (not including stderr):
```
Mono: DllImport searching in: 'libgdiplus.so.0' ('/usr/lib/libgdiplus.so.0').
Mono: Searching for 'GdipGetClip'.
Mono: Probing 'GdipGetClip'.
Mono: Found as 'GdipGetClip'.
Mono: DllImport searching in: '/usr/lib/../lib/libmono-native.so' ('/usr/lib/../lib/libmono-native.so').
Mono: Searching for 'SystemNative_Stat2'.
Mono: Probing 'SystemNative_Stat2'.
Mono: Found as 'SystemNative_Stat2'.
Mono: DllImport searching in: '/usr/lib/../lib/libmono-native.so' ('/usr/lib/../lib/libmono-native.so').
Mono: Searching for 'SystemNative_CopyFile'.
Mono: Probing 'SystemNative_CopyFile'.
Mono: Found as 'SystemNative_CopyFile'.
core name: Mupen64Plus-Next version 2.1-Vulkan a6df6b9b
extensions: n64|v64|z64|bin|u1
NeedsRomAsPath: False
NeedsArchives: False
SupportsNoGame: False
Mono: DllImport searching in: 'libdl.so.2' ('/usr/lib/libdl.so.2').
Mono: Searching for 'dlclose'.
Mono: Probing 'dlclose'.
Mono: Found as 'dlclose'.
Mono: DllImport searching in: 'libgdiplus.so.0' ('/usr/lib/libgdiplus.so.0').
Mono: Searching for 'GdipDrawPolygonI'.
Mono: Probing 'GdipDrawPolygonI'.
Mono: Found as 'GdipDrawPolygonI'.
HawkFile bound /home/yoshi/Documents/roms/N64/Super Mario 64 (USA).z64
FPS 60 SPS 44100

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x55913a0e3ffd - mono : 
	0x55913a0e43a9 - mono : 
	0x55913a08e9e9 - mono : 
	0x55913a0dd6b9 - mono : 

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x139857466193472x from 0x139858148792128x
Pkilling 0x139858100794944x from 0x139858148792128x
Pkilling 0x139857463555648x from 0x139858148792128x
Pkilling 0x139857847670336x from 0x139858148792128x
Pkilling 0x139857843467840x from 0x139858148792128x
Pkilling 0x139857985664576x from 0x139858148792128x
Pkilling 0x139857468831296x from 0x139858148792128x
Pkilling 0x139857460917824x from 0x139858148792128x
Pkilling 0x139857849771584x from 0x139858148792128x
Pkilling 0x139857845569088x from 0x139858148792128x
Pkilling 0x139857841366592x from 0x139858148792128x
Entering thread summarizer pause from 0x139858148792128x
Finished thread summarizer pause from 0x139858148792128x.
Failed to create breadcrumb file (null)/crash_hash_0x2334b6347
mupen64plus: libretro frontend doesn't have OpenGL support
Mono: DllImport searching in: '/usr/lib/../lib/libmono-native.so' ('/usr/lib/../lib/libmono-native.so').
Mono: Searching for 'SystemNative_ConvertErrorPlatformToPal'.
Mono: Probing 'SystemNative_ConvertErrorPlatformToPal'.
Mono: Found as 'SystemNative_ConvertErrorPlatformToPal'.

Waiting for dumping threads to resume
Mono: DllImport searching in: '/usr/lib/../lib/libmono-native.so' ('/usr/lib/../lib/libmono-native.so').
Mono: Searching for 'SystemNative_ConvertErrorPalToPlatform'.
Mono: Probing 'SystemNative_ConvertErrorPalToPlatform'.
Mono: Found as 'SystemNative_ConvertErrorPalToPlatform'.
Mono: DllImport searching in: '/usr/lib/../lib/libmono-native.so' ('/usr/lib/../lib/libmono-native.so').
Mono: Searching for 'SystemNative_StrErrorR'.
Mono: Probing 'SystemNative_StrErrorR'.
Mono: Found as 'SystemNative_StrErrorR'.
Mono: DllImport searching in: '/usr/lib/../lib/libmono-native.so' ('/usr/lib/../lib/libmono-native.so').
Mono: Searching for 'SystemNative_FLock'.
Mono: Probing 'SystemNative_FLock'.
Mono: Found as 'SystemNative_FLock'.
Mono: DllImport searching in: '/usr/lib/../lib/libmono-native.so' ('/usr/lib/../lib/libmono-native.so').
Mono: Searching for 'SystemNative_Close'.
Mono: Probing 'SystemNative_Close'.
Mono: Found as 'SystemNative_Close'.

=================================================================
	Basic Fault Address Reporting
=================================================================
instruction pointer is NULL, skip dumping
=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Object:wrapper_native_0x7f3331b2361a <0x0008b>
	  at BizHawk.Emulation.Cores.Libretro.LibretroApi:CMD_Run <0x00037>
	  at BizHawk.Emulation.Cores.Libretro.LibretroCore:FrameAdvance <0x0005b>
	  at BizHawk.Client.EmuHawk.MainForm:StepRunLoop_Core <0x00acb>
	  at BizHawk.Client.EmuHawk.MainForm:ProgramRunLoop <0x0053f>
	  at BizHawk.Client.EmuHawk.MainForm:ProgramRunLoop <0x00073>
	  at BizHawk.Client.EmuHawk.Program:SubMain <0x00c23>
	  at BizHawk.Client.EmuHawk.Program:Main <0x0002b>
	  at <Module>:runtime_invoke_int_object <0x00091>
=================================================================
```

**Comment by Morilli** [comment]
The core + game you mentioned does crash EmuHawk for me, even in windows, so I guess that's a core issue.

For reference, I was testing with the `bsnes_mercury_accuracy_libretro` core and multiple different SNES roms which all worked fine.

**Comment by YoshiRulz** [comment]
Hmm I'm getting a similar crash with melonDS libretro too. Could you send me bsnes-mercury? I found it in the Arch repos but it doesn't compile.

**Comment by Morilli** [comment]
There's a list of cores here: http://buildbot.libretro.com/nightly/linux/x86_64/latest/

**Review by YoshiRulz — APPROVED** [review]
Success!

**Comment by InfamousKnight** [comment]
I don't know how to test this without it being merged into master but can someone test ppsspp(lastest build) for me? I've seen on their github they have been making libretro fixes and was wondering if it does work?

**Comment by YoshiRulz** [comment]
@InfamousKnight I couldn't figure out [the assets thing](https://docs.libretro.com/library/ppsspp/#bios). The Hawk-side changes from this PR are in master as 2d81c820b, so you can give it a go yourself.

**Comment by InfamousKnight** [comment]
Thank you! Sound works, but no video output. And input works too. I didn't know what I was doing with that assets thing either. I tried following it but it don't make no difference.

**Pull request merged**
