### PR TITLE
Basicbot tasstudio issue

### PR DESCRIPTION
**Pull request by ShinobiWannabe**
Unable to resolve the issue completely.  Still When TasStudio is open sometimes the value it reads from ram is not the same that RamWatch displays.  I believe at least part of the problem has to do with TasStudio calling Updating multiple times.  I had tried various checks, but was unable to fully resolve the issue when TasStudio is open.

1.  Placed a check in the BasicBot Update() function so that it will only continue when the Emulator.Frame has actually advanced.  This prevents more inputs being generated for the bot over the expected number.  Ex: You select 30 frames for the bot to attempt, but it would generate 32.

Two other minor updates.
2. Added a Help Menu Item in the BasicBot form that will open the Basic Bot help page on TasVideos upon click.
3. Added a Copy button with the Tooltip "Copy to Clipboard.  Then possible to paste to text file or directly into TasStudio.".  It directly copies the displayed best bot input and can be used to copy paste directly into TasStudio or a text file.

----
Not really familiar with github so if there is a problem with this tell me.   
Issue #1613

### CODE REVIEW

**Comment by ShinobiWannabe** [comment]
Not really seeing what the issue is here exactly.  Just looks like it is complaining about different form designer code.

**Comment by YoshiRulz** [comment]
It says on the CI card: "AppVeyor was unable to build non-mergeable pull request " and that would be because you are "3 commits ahead, 1459 commits behind TASVideos:master". Once you've fixed that, force push branch `basicbot_tasstudio_issue` to your fork and the build will run again.

FWIW I checked and there *are* build errors, even after I fixed filename cases. I'm assuming they're old bugs and not your fault.

**Comment by vadosnaprimer** [comment]
Please don't merge yet, I'll check it this weekend.

**Comment by vadosnaprimer** [comment]
Okay I haven't found anything alarming.

**Pull request merged**
