### PR TITLE
TAStudio: allow users to delete marker 0

### PR DESCRIPTION
**Pull request by RetroEdit**
In relation to #2023.

~~I would like to look over this a bit and clean it up before considering merging; this is old code I threw together while I was originally examining the issue, but I forgot about it. The changes also touch a bit more than simply removing the marker's immutability. There were some questionable things in seeking that I still want to look at. Hopefully that doesn't dilute this issue too much.~~ All cleaned up.

~~TODO: Are savestates a problem, specifically for savestate-anchored movies? I would guess no, but it's worth checking.~~ These aren't an issue; they're handled separately.

### CODE REVIEW

**Comment by RetroEdit** [comment]
@adelikat You raised the concern that users would not be able to tell the initial state if they happened to delete the marker?

Firstly, I would say, this isn't *that* important when a user can simply verify the starting state for their movie by playing from the beginning.

My second thought was that perhaps the info could appear in the TAStudio's `Metadata > Header...` window as a readonly field.

Finally, I find it odd that I can't seem to find a `Movie info` anywhere. This could be shared between traditional `.bk2`s and TAStudio projects, and display basically every piece of info about the movie: the game name, along with the rest of the header fields, buttons to open further menus.

**Comment by InfamousKnight** [comment]
O

**Comment by adelikat** [comment]
Find a way to put the start type (power-on, sram, savestate) visibly in tastudio, and I'll approve and merge this PR.  Because it could show sram, it is actually a better ui than what the marker is trying to do.

Now that zwinder is merged, the marker is doing nothing for navigation since frame 0 is guaranteed to exist

**Comment by adelikat** [comment]
Author isn't going to finish this, and this isn't the main work.  The real problem is how we would indicate the movie start type since marker 0 is the only indicator of this. Closing this PR

**Pull request closed without merging**
