### PR TITLE
Reading gameDB include files on background threads. 

### PR DESCRIPTION
**Pull request by drakewill-CRL**
Client starts up a little faster this way. (saves 350-500ms on my machine, likely more on slower PCs).

### CODE REVIEW

**Comment by zeromus** [comment]
Decent idea, but unless there's also a line to match that somewhere else that waits synchronously to acquire access to the game database when it's needed, this is broken.

**Comment by drakewill-CRL** [comment]
I was seeing a populated dictionary when I tested it, but just to make sure it's not a timing fluke, I switched it to use ConcurrentDictionary to handle write-locking without any additional changes.

**Comment by zeromus** [comment]
That's not what I said needed to be done. To understand the problem with your code, add a "sleep" call for a second or so between loading each of the 1000s of records of the game DB. Now while that is busy taking a millennium to run, load a game that depends on it. Actually your new code is WORSE since it will potentially the bug by making it "work" (but read from incomplete data) rather than crash due to a fundamentally unsafe concurrent access

**Comment by zeromus** [comment]
Nope, not accepting a busy loop as a solution to this. Find a proper synchronization method. Also, it's an okay idea to do it near the end of the many boot steps so that it did succeed in working in the background, but while we're doing this, it would be BETTER to wait until it was actually needed, so that the time the player spends going through the menus and picking a game can be used for loading it in the background

**Comment by drakewill-CRL** [comment]
you know what? fuck it.

**Comment by zeromus** [comment]
Thanks for playing, but threading is hard.

**Comment by YoshiRulz** [comment]
:( It's their first PR ever, zeromus, why not just tell us how to `await` it properly?

**Comment by zeromus** [comment]
I don't know how to `await` anything. I use ad-hoc methods appropriate to the situation. In this case I would probably make a manual reset event and wait on it when the DB is needed, and set the event when the DB is done being loaded, but I havent checked the code

**Pull request closed without merging**
