### PR TITLE
Flip the Y axis for N64 and Saturn 3D-Pad by default. Workaround for #1200

### PR DESCRIPTION
**Pull request by NarryG**
As explained in #1200 , the N64 core and Saturn core take analog positive Y as down, whereas the PSX core takes analog positive Y as up.
In the case of xinput, which is what the default binds are, positive Y is pushing the stick away from the user. This results in a situation where the default binds provide the opposite input compared to what the user would expect.

This pull request flips the Y axis on the default binds for the N64 and Saturn 3D pad to provide input as expected by the user.

This isn't a solution to the core problem, but it results in the default binds at least being correct until the core problems explained in the issue are addressed.

### CODE REVIEW

**Comment by NarryG** [comment]
Not sure why github is including those additional commits. One of which was already merged, the other was me syncing me own repo up to master. Only one file was changed.

**Comment by zeromus** [comment]
Nope. Fix "the core issue" by inverting one of them. 

Let's use SDL as a tiebreaker.

This URL says SDL considers up positive:
http://lazyfoo.net/tutorials/SDL/19_gamepads_and_joysticks/index.php
Check a couple of other links to make sure up is really positive in SDL

Then fix whichever of xinput or dinput aren't that way by inverting their Y axis when it's read

**Comment by NarryG** [comment]
Will do

**Comment by NarryG** [comment]
While that does fix xinput and dinput being flipped, that doesn't fix the fact that some of the cores are expecting a different "up".

**Comment by zeromus** [comment]
The cores were presumably configured correctly by whoever set it up, based on whichever orientation was used by the pad they were testing on. If you flip that one on the input side, then youll have to flip the orientations in the core. Maybe it would be better to choose flipping the input method which does not result in having to change the cores. However if the cores are _inconsistent_, then choose it based on SDL and fix all the cores to suit it.

**Comment by NarryG** [comment]
The cores are inconsistent at the moment (N64 and Saturn are one way, PSX is the other). I'll go through and make them all match (+Y as up) and then make the inputs all work the same.

**Pull request closed without merging**
