### PR TITLE
Allow 2.3 to be built and run w/ MSBuild and Wine+Mono on GNU+Linux

### PR DESCRIPTION
**Pull request by YoshiRulz**
Tested on Manjaro, Linux 4.18.0-1-MANJARO, MSBuild 15.6.0.0 (`msbuild-stable` on the AUR), Mono 5.12.0 (`extra` repo), Wine 3.11 (`multilib` repo, needed for its bundled libraries).

Changes:
- Update to latest OpenTK, add input code from `mono-portable` branch (kudos), and fix bugs arisen from version differences
- Move some functionality into Win-specific classes and add Wine+Mono implementation where simple
- Add conditions to main loop so some things only run on Windows

Steps to build and run: 
```
msbuild BizHawk.sln
cd output
ln -s dll/nlua/NLua.dll   # not sure why, but putting this in LD_LIBRARY_PATH wasn't working
LD_LIBRARY_PATH="/usr/lib/wine" mono EmuHawk.exe
```
I promise no functionality beyond Help>About.

***

Cores known to crash:
* Cygne
* Gambatte
* Genesis Plus GX
* Handy
* Mupen64Plus
* Neo-Geo Pocket (dunno what it's called)
* NESHawk
* Octoshock
* Snes9x
* TI83Hawk (or I got a corrupted ROM)
* VBANext

Cores that may work:
* Atari2600Hawk
* A7800Hawk

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
Every time I something like this, I call my friends and we celebrate!

Does this mean the current releases of bizhawk start working on linux? It's just unbelievable, due to all the crazy problems Wine had with bizhawk 2.x.

Also, can you attach the build package so we could test it on linux?

**Comment by YoshiRulz** [comment]
@vadosnaprimer: If by "build package" you mean a compiled copy, I've uploaded it to [my personal Google Drive here](https://drive.google.com/open?id=13NVqPqgxBdpFr1VCGzqoO9c8t23xvYfq) where it'll be available for a while. If you meant a build script as in PKGBUILD, I'll be submitting one to the AUR once I can get close to feature-parity w/ Windoze.

**Comment by vadosnaprimer** [comment]
Every time I something like this, I call my friends and we celebrate!

Does this mean the current releases of bizhawk start working on linux? It's just unbelievable, due to all the crazy problems Wine had with bizhawk 2.x.

Also, can you attach the build package so we could test it on linux?

**Comment by xy2iii** [comment]
I am trying to run the binary provided above with [Nix](https://nixos.org/nix/) for reproducibility, however I am running into runtime errors:

screenshot_20180702_185516

Mono 5.8, wine 3.3. I am confused as the libs are present in the `lib/wine` path yet they don't seem to be getting picked up.

**Comment by YoshiRulz** [comment]
@xy2ii I don't know what to tell you. Perhaps the copy of Wine on Arch/Manjaro comes with these extra libraries but your distro separates them into another package? I suggest you search your computer for `d3dx9_43.dll` to see if it's simply stored elsewhere.

**Comment by xy2iii** [comment]
Well, stuff works now. Core load crashes, as mostly expected:
screenshot_20180704_192753

**Comment by Gnuk** [comment]
On Arch Linux, latest update, i've an error message when I open a game:

Games I open:

* Castlevania Aria of sorrow (GBA)
* Chou makaimura (SFC) (Japanese version of Super Ghoul's n ghosts)

Trace:

```
System.NullReferenceException: Object reference not set to an instance of an object
  at BizHawk.Client.EmuHawk.MainForm.<ProcessInput>b__94_0 (System.Tuple`2[T1,T2] o) [0x00028] in <20767738e2694b109e8265fc343e1fa5>:0 
  at System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].MoveNext () [0x00048] in <10ce10dbd2d94d228d3c3a736756184a>:0 
  at BizHawk.Client.Common.SimpleController.AcceptNewFloats (System.Collections.Generic.IEnumerable`1[T] newValues) [0x0002c] in <d7c83fb72cd94c44805bf849b8692fc9>:0 
  at BizHawk.Client.EmuHawk.MainForm.ProcessInput () [0x00277] in <20767738e2694b109e8265fc343e1fa5>:0 
  at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop () [0x00055] in <20767738e2694b109e8265fc343e1fa5>:0 
  at (wrapper remoting-invoke-with-check) BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
  at BizHawk.Client.EmuHawk.Program+UnixMonoMainLoopCrashHandler.TryCatchFinally (System.String[] args) [0x00021] in <20767738e2694b109e8265fc343e1fa5>:0 
```
screenshot_20180729_112932

**Comment by YoshiRulz** [comment]
@Gnuk I never said you'd be able to load a ROM... though I suppose it's good to know exactly which cores crash (I'd simply assumed all of them would). I've edited these into a list in the first comment, assuming you were using VBANext and Snes9x.

**Comment by vadosnaprimer** [comment]
We're not yet releasing, so we'll have time to test.

**Pull request merged**
