### PR TITLE
Lua: Add optional position parameters to `DrawPolygon`

### PR DESCRIPTION
**Pull request by AntyMew**
In some cases, a user may want to draw a polygon at a different position without needing to update every point. The proposed changes optimize this task by applying the translation while populating the array of points.

Note that this change breaks backwards compatibility of `gui.drawPolygon`, `forms.drawPolygon`, and `LuaCanvas.DrawPolygon` by placing the new `x` and `y` parameters before `line` and `background`. This was done to maintain the convention of color arguments going last.

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
Nice! Can you post an example script? Also, does it build for you? Built bot dies here:
https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/0.0.0.2142#L470

**Comment by AntyMew** [comment]
Gotcha! This should demonstrate the new behavior effectively...

```lua
triangle = {{0, 19}, {19, 19}, {19, 0}}

while true do
    gui.drawPolygon(triangle, emu.framecount() % 240, 0)
    emu.frameadvance()
end
```

**Comment by AntyMew** [comment]
...I have no idea what this CI is complaining about. Maybe the breaking change has to do with it?

**Comment by AntyMew** [comment]
PFFFFT, I missed that typo rereading it about 10 times. Whoops...

**Comment by vadosnaprimer** [comment]
Doesn't work for me if these offsets are omitted: `gui.drawPolygon({{100, 119}, {119, 119}, {119, 100}})` does nothing after this change, but works before it. I think those variables need to be nullable type to become truly optional? Also, I think it'd be better to call them offset rather than position, because position is already included in the polygon table.

**Comment by adelikat** [comment]
Going to merge this into a branch and then take a shot at the suggestions feos had

**Pull request merged**
