### PR TITLE
GB layers

### PR DESCRIPTION
**Pull request by brunovalads**
- Fixed OBJ layer toggle message;
- Added WIN (window) layer toggle hotkey option;
- GPU Viewer add-on to display sprite tiles on the real position, just like what you have for the bsnes core. Has several issues:
  - Drawing is identical to the current sprite display, so it doesn't have the transparency it should have;
  - Drawing doesn't take priority into account, so overlapping is usually wrong;
  - The drawing flickers, probably the way of refreshing (with `.Clear()`) is bad.

### CODE REVIEW

**Comment by nattthebear** [comment]
Wish we handled layer toggle keybinds in a less ad-hoc manner, but this isn't the place for that

**Comment by brunovalads** [comment]
> layer toggle keybinds

I was thinking in the Hotkeys menu instead of multiple tabs for each console (for some reason only SNES, GB and NDS have), you could have a "Console specific" tab, then inside it it would be divided into the different consoles that benefit from hotkeys (like layer toggling, audio channel toggling, etc).

**Comment by brunovalads** [comment]
[Image reference for the GB sprite object viewer](https://i.imgur.com/bpMjyAd.png)

**Comment by nattthebear** [comment]
> The drawing flickers, probably the way of refreshing (with .Clear()) is bad.

Try clearing directly in the draw routine (just write whatever backdrop color you want to every pixel of dest)

**Review by adelikat — APPROVED** [review]

**Pull request merged**
