### PR TITLE
Ports from Upstream GSR for Babs and Robopon

### LINKED ISSUE #2065: Robopon - Sun Version (GBC) not loading
Error message: "load error. Failed multiple attempts to load ROM"

### PR DESCRIPTION
**Pull request by TiKevin83**
fixes #2065

### CODE REVIEW

**Comment by TiKevin83** [comment]
https://github.com/pokemon-speedrunning/gambatte-speedrun/issues/41

**Comment by nattthebear** [comment]
LGTM

**Comment by alyosha-tas** [comment]
Any chance this could be rolled into something that more generally fixes unused_hwio-C.gb and boot_hwio-C.gb ? It's fine if not, nothing to hold it up over, just curious as there are generally a lot of other little things that might be similar in those.

**Comment by TiKevin83** [comment]
I just got Robopon booting and will roll that in, I still haven't looked at unused HWIO

**Comment by TiKevin83** [comment]
Ok this should have both the Babs fix and the Robopon huc3 mapper fix now

**Comment by alyosha-tas** [comment]
Tested and works on my end (even found a GBHawk bug with sRAM along the way.) Ready to merge?

**Comment by TiKevin83** [comment]
I've tested it against unrelated console-accurate movies and it doesn't appear to have caused any regressions.  I'm good with merging.

**Pull request merged**
