### PR TITLE
add a Lua method to get inputs from the movie

### PR DESCRIPTION
**Pull request by SuuperW**
It seems we didn't have a way for Lua scripts to get the inputs created by movies.

### CODE REVIEW

**Review by YoshiRulz — APPROVED** [review]
LGTM, though I feel like a better name than `GetWithMovie` exists.

Does anyone remember why we're removing entries from tables in this library?

**Comment by YoshiRulz** [comment]
I tracked down the commit which added the `table[...] = null;` nonsense: 78d8effcf. There's no explanation. It was so long ago that we should just assume it wass a workaround for a problem that has since been fixed, and remove it.

**Comment by adelikat** [comment]
Why is this a joypad method and not a movie method?

**Comment by YoshiRulz** [comment]
I think it makes sense where it is. Its semantics aren't specifically about movie input, the inputs it's reading are the sum of the whole stack including autofire/autohold and Virtual Pads (IIRC).

**Comment by adelikat** [comment]
Fair enough.

**Review by adelikat — APPROVED** [review]

**Comment by ThunderAxe31** [comment]
I think there was already one Lua function for getting inputs from a movie file: `string movie.getinputasmnemonic(int frame)`

**Pull request merged**
