### PR TITLE
Resize unattended video if zoom factor >1

### PR DESCRIPTION
**Pull request by Vilsol**
Make it possible to resize the video even in unattended mode.

### CODE REVIEW

**Comment by Vilsol** [comment]
@vadosnaprimer I am sorry that you have to resort to personal attacks. As a third-party contributor, my job is to propose changes to the repository. Then it is the job of the core contributors to review whether that change is valid. My PR was pulled and merged without question or comment. If you expect all of your third-party contributors to know your codebase by heart, I don't see anyone wanting to be insulted for trying to better the community and software.

**Comment by zeromus** [comment]
how do you know he wasn't talking to me?
target zoom factor is the client window size. it has nothing to do with dumping. if you want your video scaled, bizhawk is the wrong place to be doing it. do it in postprocessing.

**Comment by Vilsol** [comment]
I assumed that because the comment was on my commit with no additional tags to any other person, it would be relating to me. I apologize for any trouble I caused and I won't be causing any more.

**Comment by zeromus** [comment]
you're too sensitive. I caused the trouble by merging the commit.

**Comment by vadosnaprimer** [comment]
@Vilsol apologies accepted. Sorry but it wasn't possible to react in a better way. You're probably entirely new to coding, in which case it's better to just make an issue and ask something. The option you want is 2x window size + capture OSD enabled (make sure to disable all the actual HUD you don't want). This will result in a dump at whatever the size of the client area is.

**Comment by vadosnaprimer** [comment]
LOL, downvoted for telling how to do the scaling, what a petty flashmob.

**Comment by zeromus** [comment]
Wow, he wasn't kidding about the flashmob. Now we've attracted a visiting lecturer.

**Comment by vadosnaprimer** [comment]
> libelous, defamatory, or fraudulent
> discriminatory or abusive
> harass, abuse, threaten, or incite violence
@nickrobson please link me to the actual definitions of those terms that you used when deciding that anything I said matches them. Or will I be reported for asking that too?

**Comment by nickrobson** [comment]
> @vadosnaprimer wrote: 
> @nickrobson please link me to the actual definitions of those terms that you used when deciding that anything I said matches them. Or will I be reported for asking that too?

You should be able to find sufficient definitions in your English dictionary of choice. 🙂

**Pull request merged**
