### PR TITLE
Change build config to support the Core build system (as well)

### PR DESCRIPTION
**Pull request by YoshiRulz**
This is a helpful first step towards #1415. It's also a requirement for GitLab CI, which uses Docker.

req:
- [x] msbuild on Windows
- [x] dotnet on Linux
- [x] dotnet on Windows

Ready to squash, though trying the changes on more machines couldn't hurt.

bonus:
- [ ] msbuild on Linux (I think it will be deprecated soon anyway)
- [ ] double-check build tool replacement

### CODE REVIEW

**Comment by zeromus** [comment]
Please attach memorandum describing why gitlab CI matters

**Comment by jdpurcell** [comment]
I'd be against this if it has side effects in Visual Studio or MSBuild. After I moved everything into conditional imports it seems better but it needs more testing.

**Comment by jdpurcell** [comment]
It's behaving well with Visual Studio / MSBuild now. @YoshiRulz can you make sure it still works for you as of my most recent commit?

**Comment by YoshiRulz** [comment]
Does now.

**Comment by jdpurcell** [comment]
@YoshiRulz Perhaps we should merge this to the MoreUnixMonoCompatWork branch for now?

**Pull request merged**
