### PR TITLE
DiscSystem: MDS/MDF Support

### PR DESCRIPTION
**Pull request by Asnivor**
Adds experimental support for Alcohol 120 images.

* New MDS_Format class in Emulation.DiscSystem
* Emuhawk will now consume *.mds files
* DiscoHawk will accept and hawk *.mds files

Limitations:

* Tested only with PSX images only so far
* Currently only CD images are supported (DVD images will bubble up an Exception which is handled during parsing)

### CODE REVIEW

**Comment by MelchiorGaspar** [comment]
yeah I happen to like MDS/MDF format myself..
I have dumped 17 of my 31 PS2 games in this format...

but for PS1,  I have been rather unsure which format to use when dumping my PS1 games.. O_o
that is which is best/optimal
- ccd/img/sub, bin/cue, mds/mdf

I have dumped one of my games FFT in all three formats for testing
- ccd/img/sub, bin/cue, mds/mdf

Thanks for adding this format to BizHawk, 
as ePSXe already supports mds/mdf too.   lol   :D   ;-)

**Comment by zeromus** [comment]
You shouldn't dump your own PS1 games.
If you MUST, don't expect support with them, and use ccd

**Comment by MelchiorGaspar** [comment]
lol, if you say so....
BUT why shouldn't I?
I have a TOP of the line Blurary, DVD, CD writer :-P  
- ASUS  Blu-Ray Writer BW-16D1HT,  [https://www.amazon.com/gp/product/B00DWFPDJI/](url)
- $79.99 when I bought it earlier this month.. ;-) 

and I have kept **all** of my games in pristine conditions,
that is always respecting my discs :D ;-)

why ccd? most of the images I have download for PS1 games I have but didn't feel like dumping 
myself were **ALL** in the bin/cue format and all seem to work just fine..

**Comment by Asnivor** [comment]
@MelchiorGaspar this PR is VERY experimental. In fact, I've not been able to test it on any MDS/MDF images that have audio tracks yet.

Don't expect too much yet :)

**Comment by MelchiorGaspar** [comment]
@Asnivor  ok I have a copy of FFT I dumped in the MDF/MDS format I can run it through and give it a
testing... well just as SOON as a build is ready.. lol ;-P
does BizHawk have a development BUILD-BOT up and running yet?
it a great thing to have as it will make testing RAPID..

and for testing.. should  I delete any specific directory or just drag, drop, and overwrite?

**Comment by zeromus** [comment]
Go read about redump and 100 page long forums full of people finding exactly which 25 year old CD reader malfunctions the least and which programs yield the most reliable results. This is not a casual hobby anyone with a CD reader can do, it is a very in-depth and detailed hobby.

Cue is stupid. So it works for PSX, it doesnt work for other things.

**Comment by MelchiorGaspar** [comment]
The MDS/MDF format is the **BEST/ULTIMATE!** 
Muwahahaha ;-P

or at least I like it..

for dumping tools I have 
- Alcohol 120% (v2.0.3.9902)(paid)(is up to date)
- DAEMON Tools Lite (v4.49.1.0356)(free but I payed under $10 for it to support them)
- DAEMON Tools Lite's most recent version is (v10.6.0.0275) I just didn't like the new GUI much.. :( 

I use DAEMON Tools Lite for all my PS2 dumping MDS/MDF and ISO for my one PS3 game FF13
and while I have dumped PS1 games MDF/MDS format with DTL.. 
I used Alcohol 120%  to image in the ccd and bin/cue format... as DTL only does MDS, MDX, and ISO..

**Pull request merged**
