### PR TITLE
Gambatte-Speedrun: Wisdom Tree Mapper Support, Doc Update, Output to Assets, Fix RTC

### LINKED ISSUE #1260: [FEATURE REQUEST] Wisdom Tree unl mapper in Gambatte core support
they used custom 32K banking mapper so does not work in bizhawk

### PR DESCRIPTION
**Pull request by TiKevin83**
fixes #1260 , #1895 
Concerned because 0567623 appears to not completely handle the libgambatte.dll here, I had to move it manually for this PR. Probably need to also update the build script to drop the libgambatte dll there and update the dll import to pull from there if the dll actually needs to be moved to the assets folder.

Edit: I changed the output directory to Assets for this PR

### CODE REVIEW

**Comment by YoshiRulz** [comment]
Yes, all unmanaged cores' build scripts will need to be updated. (I hadn't documented that anywhere though, so it's now in #2423.)

---

Did you check in the correct binary? GitHub seems to think it's an "empty file".

**Comment by nattthebear** [comment]
The changes in the submodule seem to be fine as best as I can tell.

**Comment by TiKevin83** [comment]
not sure what happened with the dll "empty file" - going to mark this WIP for a bit, we're working on fixing some outstanding bugs in RTC

**Comment by TiKevin83** [comment]
CPP finished fixing RTC to work through hard reset, core reboot, and the real time RTC feature if anyone wants to take another look before merging.

**Comment by TiKevin83** [comment]
Not sure why the dll says "empty file" but it appears to be building to the correct location now and contains the mapper and RTC updates

**Pull request merged**
