### PR TITLE
fix console garbage

### PR DESCRIPTION
**Pull request by nattthebear**
Add EmuHawkConsole.exe which forces EmuHawk.exe to run with a console.  Switch output type back to winexe

### CODE REVIEW

**Comment by nattthebear** [comment]
@adelikat @vadosnaprimer I know you two were most interested in this

**Comment by vadosnaprimer** [comment]
Doesn't seem to launch when running hawk from VS. When I run EmuHawkConsole.exe, it launches hawk, but it doesn't run through VS, so breakpoints don't work. Closing hawk crashes the console.

**Comment by nattthebear** [comment]
Right, you'd have to attach yourself.  Didn't think of that one too much; all of my debugging right now is attach

**Comment by nattthebear** [comment]
> Closing hawk crashes the console.

Yeah, have to fix exactly what handles are closed by what when

**Pull request closed without merging**
