### PR TITLE
[WIP] Trying to get Virtu fixed up a bit

### PR DESCRIPTION
**Pull request by Asnivor**
**WIP - DO NOT MERGE YET**

So this might not go anywhere, but there is so much wrong with the Apple II core right now, I thought i'd take a look over the next week or two.

If no-one minds I'll keep this PR open until it's done (or we give up). Its just easier for me to track stuff and ask questions here.

So, problems faced:

- [x] Apple 'Open' and Apple 'Close' buttons are not currently implemented
- [ ] Reset button not currently implemented
- [ ] Joysticks are not implemented
- [ ] Paddles are not implemented
- [ ] Controls are buggy generally (see prince of persia - character auto-walks left at the start until you press up-arrow and Donkey Kong)
- [ ] It looks like *.nib support is in the original Virtu source, but the core will not load these files correctly
- [ ] Currently, all client methods that read the system bus (RAMWatch, RAMSearch, HexEditor etc.) have the potential to trigger the peripheral card soft-switches in the core. Altering core state just by observing it is some next-level quantum terribleness..

Can't promise anything, but the core has been annoying me for a while now. Speak up here if anything else is wrong that I have missed above.

Current reference issues: 
#1121 
#1186 
#1169

### CODE REVIEW

**Comment by alyosha-tas** [comment]
Just throwing this out there as an idea, but would it be worth it to just make an in-house core for Apple II instead? We already have a 6502 and can borrow from the existing core infrastructure. Virtu seems like kind of a dead end to me.

**Comment by Asnivor** [comment]
@alyosha-tas You know, that might actually be doable. I'll think about it a bit more next week.

**Comment by Asnivor** [comment]
So mednafen has Apple II/II+ now (with potentially IIe coming later). Its probably a waste of my time to start a new apple II core if there is any chance of waterboxing this....

**Comment by adelikat** [comment]
So, this has been sitting for awhile now.  Are the other 6 things on the checklist going to happen?  Can we just merge this one since it is a solid improvement?

**Comment by Asnivor** [comment]
Yeah, I'm not sure I will have time for this anytime soon. Also, github is showing a merge conflict on bizhawk.sln and I don't have time to fix that and merge right now. If someone else wants to fix and merge that would be cool....

**Pull request merged**
