### PR TITLE
Fix Linux build

### PR DESCRIPTION
**Pull request by lefta**
This is the first step to a Linux port (#715) : the easy part : building.

None of the clients run at the moment, but I wanted to make a first PR as it may serve as a base if someone else want to try. Each commit should be self explanatory and there is a `README_LINUX.md` file with status details and Linux specific instructions.

Mac OS have not been tried at all.

### CODE REVIEW

**Comment by Sappharad** [comment]
Why did you decide to use master instead of the mono branch? Didn't want to use the existing changes?

**Comment by vadosnaprimer** [comment]
Hey, now it's done for bizhawk [too](https://github.com/TASVideos/desmume/pull/1)! Thanks for your efforts!

**Comment by lefta** [comment]
@Sappharad The Mono branch have not been updated for some time. I did not felt to deal with potential conflicts and could not see what work was already done in it. More important, doing the easy things that are likely already done in the Mono branch helps me to understand the project before handling more advanced stuff.

@vadosnaprimer I had a dream: Linux was widely used and got as much traction from developpers (especially software companies) as Windows does. This is one step further ;)

**Comment by Sappharad** [comment]
But I just pulled latest into mono branch last Monday. 😟
I merge after every release.

Oh well, glad your changes build

**Comment by lefta** [comment]
Checked last weekend, I did not see that you updated it in the meantime. What is the status of your branch?

**Comment by Sappharad** [comment]
I've done MacOS builds of almost every release for the last 3 years from the mono-portable branch. The status is that I've been keeping what already works running for the last year or so, but haven't made new changes. Last week's build has not had binaries posted because I figured there would be another release right away for the mGBA stuff in the bugs thread, but the last merge was running the few games I tested.

It may be feasible to go to trunk with some of the changes but that has not been discussed recently. There are some UI hacks that don't really belong in master.

**Comment by Sappharad** [comment]
I guess my point is that you may want to look at the branch to see what changes were made before you proceed with master. It has built fine on Linux when I last tried it 2 years ago, but did not work very well. That branch at least works on mono-osx for sure since I use it.

**Comment by lefta** [comment]
I'm currently checking right now, but the mono-portable branch do not build on Linux, there are case-sensitivity issues, meaning at least the version cleanup and the case fix commits have to be cherry-picked. I'm going to try to merge all this together and see what I may do from here.

**Comment by Sappharad** [comment]
Good luck.
If you manage to get it working, we should try to come up with a better long term plan to supporting Linux and MacOS. I can continue to keep things working on Mac, but I don't have a lot of time to spend on new stuff. I had started creating a new UI last year that would be native on other platforms but stopped before figuring out how to get OpenGL working with it. You can find in the EtoHawk directory, but it never got very far along.

I'll take a look at your changes tonight to see if I can merge them into the branch. The case sensitivity problem has come up in the past, although I thought we fixed it already.

**Comment by lefta** [comment]
I have fixed the case sensitivity already, my changes are not very big and it seems that you almost have all of them. I'm already in the process of merging, I will come with a new PR against your branch once done.

**Comment by lefta** [comment]
Ok, managed to build it, I didn't see that there was a solution in the EtoHawk directory, but I couldn't run a (GBA) ROM. I will maybe retry next time I have nothing to do.

**Comment by Sappharad** [comment]
GBA uses native cores. None of those have been ported to Linux. You will want to try sega gamegear, TG16, or Atari 2600, those are some of the .NET cores

**Comment by Sappharad** [comment]
I went ahead and did a merge of the latest changed from master into mono-portable. So everything as of right now is again current on the branch. I quickly ran a GameGear game to test it out.

One of the changes you'll find in the branch (it's one of the reasons I've kept the code away from master) is most of the Open and Save dialogs are created via the HawkDialogFactory class. This is because on macOS I created a project called "MonoMacWrapper" that wraps the WinForms UI inside of a partially native macOS project. The project extracts the menus from the WinForms app and inserts them in the macOS's native menu bar. Then the File Open/Save dialogs are also replaced with native dialogs on Mac. This was sort of hack that has no reason to exist on Windows which is one of the reasons I've left it out.

The actual emulation code (BizHawk.Emulation.* projects) will compile fine in mono against master without changes. My ultimate hope would be for EtoHawk to make it to the point where it could go into master as an alternative UI for other platforms and share the non-UI code with the rest of the emulator so a mono branch with platform-specific hacks wouldn't be necessary, but this hasn't happened because I haven't worked on it. If you or anyone else is interested in making a multi-platform UI (even if it's not Eto, which was chosen because it looked like the best option when I started) I'd be willing to help in any way I can. Otherwise it may be a while before I start looking at it again. The WinForms UI wrapper on macOS is a bit glitchy in places, but otherwise it works decent enough to use the emulator for gaming.

There's a forum thread discussing the MacOS builds where some comments have been made regarding Linux in the past. But so far anyone who's submitted fixes has not stuck around long enough to get BizHawk working on Linux as far as I know. I'd love to do anything I can to help, time permitting. Anything you fix for Linux will probably benefit macOS as well, unless it's something that's already working.

Regarding the native cores, (QuickNES, mGBA, VBA, Gambatte, Genesis Plus, PSX, N64, Saturn, SNES) I've ported the first 6 in that list to macOS. You'll see a bunch of .dylib files in the /output/ directory for those cores. Those are the macOS builds of the native DLL's. On Linux, I believe you need to build .so files for them. Mono will look for the .so files with the same name as the original .dll (sometimes with lib prefix) and load them automatically. The 3 cores I didn't port to macOS have various reasons why. N64 and Saturn are probably possible, they were just complicated. The BSNES core I actually had compiling for macOS at one point, (the Xcode project might even still build now) but communication for that was using named pipes which Mono doesn't support so I stopped.

Please let me know if there's anything else I can explain that might help.

**Comment by jmichaux** [comment]
I have a stupid question...but how exactly does one download/install the latest BizHawk build for Mac OSX? Are there instructions somewhere?

Thanks!

**Comment by Sappharad** [comment]
@jmichaux 
Read the forum thread about the MacOS builds, starting from the end and working your way backwards because I'm not allowed to update the opening post anymore.

http://tasvideos.org/forum/viewtopic.php?p=449219#449219

Download the latest build, unzip and copy it to your Applications folder to install it. (Copying to applications folder is only required on macOS 10.12 due to Apple security features)

If mono is not installed, it will prompt you to install it when you try to run it for the first time.

**Comment by jmichaux** [comment]
@Sappharad Thanks for getting back to me.

**Pull request closed without merging**
