### PR TITLE
Implement missing part of DiscoHawk CLI

### PR DESCRIPTION
**Pull request by YoshiRulz**
@Meerkov

### CODE REVIEW

**Comment by Meerkov** [comment]
I look forward to trying this out later, but I noticed in the change that `discInterface ` is unused. Is it needed?

**Comment by zeromus** [comment]
Is there any particular reason why this should be so controversial or tricky that it requires a review that I should pay attention to?

**Comment by YoshiRulz** [comment]
> Is it needed?
Yes, oops.

> Is there any particular reason why this should be so controversial or tricky that it requires a review that I should pay attention to?
Nope

**Review by zeromus — APPROVED** [review]

**Review by zeromus — APPROVED** [review]

**Comment by Meerkov** [comment]
I've tested the HAWK function, and it looks like it works to me. Thanks!

**Pull request merged**
