### PR TITLE
[WIP][🐧] More Linux/Mono Compatibility Work

### PR DESCRIPTION
**Pull request by Asnivor**
TODO rewrite this checklist, removing things that were committed to master in the interim

### Progress
- [x] Resolving Assemblies
  - [x] AssemblyResolve - find .NET DLLs not in the executing directory (https://github.com/TASVideos/BizHawk/commit/39afe3eb732bdb0b3387505148311612ecc3ad24)
  - [x] Microsoft.VisualBasic namespace should be usable in Mono (https://github.com/TASVideos/BizHawk/commit/1be2738a23209e6307b87023a96f2b7a08f434ff)
  - [x] SevenZipSharp assembly exception (need to remove SevenZipSharp) (https://github.com/Asnivor/BizHawk/commit/e76df2732a302a3d4435740d7035544deaca846d)
- [x] Misc UI related stuff
  - [x] Menubar mnemonics (disabled on unix to prevent a crash caused by a WinForms reflection hack) (https://github.com/Asnivor/BizHawk/commit/632768d5f8b325441ebbb103b0bb24aeaff7a2d6)
  - [x] Path settings throwing exceptions and getting non-relative paths when setting through the folder browser dialog (https://github.com/Asnivor/BizHawk/commit/dccaa2b87807d261adc2611ccec14782dbcc7e5b & https://github.com/Asnivor/BizHawk/commit/519e114721104b9cb69385ef798f820547b725d9)
- [ ] ToolBox
  - [x] Opens with NullHawk (https://github.com/TASVideos/BizHawk/commit/39afe3eb732bdb0b3387505148311612ecc3ad24 and I think https://github.com/TASVideos/BizHawk/commit/42b5931c1741be1694ede9904e54ce5e8d86b906)
  - [ ] Opens with core loaded
- [x]  Archive Handling
  - [x] Replace SevenZipSharp with .NET native SharpCompress for mono (https://github.com/Asnivor/BizHawk/commit/e76df2732a302a3d4435740d7035544deaca846d)
  - [x] Check implementation also works on Windows (yes, but currently not wired up) 
- [x] Sound
  - [x] OpenAL using latest OpenTK (https://github.com/Asnivor/BizHawk/commit/3aefa3c75f2f5bb39559701dbb6d46b4b8b8b3b3)
- [x] Video (https://github.com/Asnivor/BizHawk/commit/196d51da94851b118dbaa917cc9dc72fa3fc89c2)
  - [x] OpenGL support (using latest OpenTK)
  - [x] Fix display preferences so that unix users can choose either OpenGL or GDI+
- [x] Firmware options
  - [x] Mitigate exception raised when attempting to open a non-existing firmware folder (https://github.com/Asnivor/BizHawk/commit/f01f0fa7864abf804239d90ff47f23dea2a19809)
- [x] Multi-disk Bundler
  - [x] Handled crash due to `GetRelativePath` calls using Win32 native functions, resulting in mono trying to reference shlwapi.dll (and failing). Means that you can never generate a bundler xml file (https://github.com/Asnivor/BizHawk/commit/ebd94a8ecddbc291ece18867138e5d3e1feebf5c)
  - [x] Exceptions in `PathConfig.cs` due to linux filesystem (https://github.com/Asnivor/BizHawk/commit/5aaa914de52b2586824721b9baf7fe9832b51fe0)
- [x] Controllers
  - [x] (Re)Wire up 'OTK_GamePad' (https://github.com/Asnivor/BizHawk/commit/2fe818c3241260df1ebe3e26a7dfde497eb48dc9)
  - [x] Re-write OpenTK GamePad/Joystick implementation so fully working on linux (note: some controllers require a little axis or button input as EmuHawk starts - otherwise OpenTK does not detect them at initialization) (https://github.com/Asnivor/BizHawk/commit/e483c94498da74a2ed66cf88d52edda551b0cc50)
  - [x] Tested and working on Windows also (although not currently wired up)
- [x] TAStudio
  - [x] Re-write InputRoll to use GDI+ renderering on linux (rather than the Win32 native GDI calls that wont work)
  - [x] Make GDI+ InputRoll rendering available on Windows as well (via a TAStudio option stored in Global.Config)
- [x] VirtualListView - this custom control uses Win32 native calls in it's virtual listview implementation. This causes all BizHawk components that use this control to not show anything in the listbox (or crash). These components are as follows (and require serious work):
  - [x] CDL
    - [x] Exception on opening
  - [x] Cheats
  - [x] GenericDebugger & BreakpointControl
    - [x] Opens without exception
    - [ ] VirtualListView control does not update
  - [x] LuaConsole  
    - [x] Opens without exception
    - [x] Can load and run lua scripts
    - [x] VirtualListView control does not update
  - [x] LuaFunctionsForm
  - [x] UndoHistoryForm
  - [x] Tracelogger
    - [x] Opens without exception
    - [x] Log to files
    - [x] ~~VirtualListView control does not update~~ Replaced with PlatformAgnosticVirtualListView
  - [x] RAMSearch
    - [ ] VirtualListView control does not update
  - [x] RAMWatch
    - [x] VirtualListView control does not update
  - [x] PlayMovie
- [x] Vulkan renderer but it's actually a copy of OpenGL - #1468
- [x] Remove the last references to WINE bundled libraries
- [x] Do OS check properly (macOS enum constant is never used, check `uname -s` for `Darwin` instead)
- [ ] Cores Working
  - [x] NullHawk
  - .NET Native
    - [x] A7800Hawk
    - [x] Atari2600Hawk
    - [x] C64Hawk
    - [x] ColecoHawk
    - [x] GBHawk
    - [x] IntelliHawk
    - [x] NesHawk
    - [x] PCEHawk
    - [x] SMSHawk
    - [ ] TI83Hawk
    - [x] Virtu
    - [x] ZXHawk
  - C/C++
    - [ ] BSNES
    - [x] Gambatte
    - [x] Handy
    - [ ] mGBA
    - [ ] Mupen64Plus
    - [ ] Octoshock
    - [x] QuickNes
    - [x] VBA-Next
    - [x] Cygne
  - WaterBox
    - [ ] Genplus-gx
    - [ ] NeoPop
    - [ ] SameBoy
    - [ ] Saturnus
    - [ ] Snes9x
    - [ ] VirtualBoyee

### CODE REVIEW

**Comment by Asnivor** [comment]
Toolbox now opens #1430

**Comment by YoshiRulz** [comment]
Toolbox already opened on NullHawk, try loading a rom.

[Program.cs w/ more inlining](https://gist.github.com/YoshiRulz/81f803c60f2453e9800e674196fe8e64)

**Comment by Asnivor** [comment]
For me it didn't. It was throwing an exception even on nullhawk

**Comment by YoshiRulz** [comment]
8e11896: should be able to
```sh
...
	case...
		...
		"Debian"|"LinuxMint") libpath="/usr/lib/x86_64-linux-gnu/wine";;
		"Ubuntu") libpath="/usr/lib/x86_64-linux-gnu/wine"; MONO_WINFORMS_XIM_STYLE=disabled;;
	esac
...
LD_LIBRARY_PATH="$libpath" mono ./EmuHawk.exe
```
instead

**Comment by Asnivor** [comment]
@YoshiRulz ahh, ok yeah. That's far better.

**Comment by YoshiRulz** [comment]
Might be needed for Mint too, I'll check that now

**Comment by Asnivor** [comment]
So on ubuntu (18.04 at least) this shows itself as EmuHawk crashing before the form is displayed with something like "too much data requested from _xread".

**Comment by YoshiRulz** [comment]
> NES, FDS, SNES, SMS, Game Gear, PCE/TG16, Atari 2600, Atari 7800, Atari Lynx, ColecoVision, Genesis/MegaDrive, Sega CD, Gameboy, Gameboy Color, GBA, Wonderswan are all supported.

-- Sappharad re: macOS fork, [Jan 2018](https://github.com/TASVideos/BizHawk/issues/1092#issuecomment-357383811)

What we're aiming for.

**Comment by YoshiRulz** [comment]
should probably dig #93 out of the attic

**Comment by Asnivor** [comment]
Is that still even relevant?

**Comment by YoshiRulz** [comment]
On Unix, you do this with [coreutils](https://stackoverflow.com/a/28523143):
https://github.com/TASVideos/BizHawk/blob/dccaa2b87807d261adc2611ccec14782dbcc7e5b/BizHawk.Client.Common/PathManager.cs#L419-L427
As noted:
https://github.com/TASVideos/BizHawk/blob/dccaa2b87807d261adc2611ccec14782dbcc7e5b/BizHawk.Client.EmuHawk/tools/MultiDiskBundler/MultiDiskBundler.cs#L303-L306
...these reimplementations may still be useful so just we'll leave them in `#if false`.

**Comment by YoshiRulz** [comment]
The diff is a little messy, but [this](https://github.com/TASVideos/BizHawk/tree/deed16d56b3216ee5c9a4bab04c978ffd0c8be31) is what copying our input/HID work to MultiHawk looks like. Probably out-of-scope for this PR, I just wanted to see if it worked.

**Comment by YoshiRulz** [comment]
.NET Core 3.1 is set to release in November (an outline of .NET Core's future is in https://github.com/TASVideos/BizHawk/pull/1422#issuecomment-490741652), so if we port as much of the codebase as possible before then, we can put all our effort into migrating to .NET Core.

**Comment by YoshiRulz** [comment]
Fullscreen isn't centered, and alt+enter from fullscreen leaves the window maximised (instead of at 3x or whatever `View` > `Window Size` is set to).

**Comment by YoshiRulz** [comment]
Mono uses a copy of Windows' colour picker for `ColorDialog`, which sucks IMO. There must be better ones to choose from on NuGet, hopefully ones that are consistent across OSes.

**Comment by YoshiRulz** [comment]
Not opening an issue because I assume it only affects Linux, but I hit this crash (on master, see bisect log in comment): https://gist.github.com/YoshiRulz/c0f91baa9cbc37c19f3b9c04aeeaef00

**Comment by YoshiRulz** [comment]
I think a Mono update broke it even further :( I'm not even getting to `MainForm` anymore, it crashes in [`Program.SubMain`](https://github.com/TASVideos/BizHawk/blob/a1155c5c97126730e6e9d7767cd706ce95eeee6a/BizHawk.Client.EmuHawk/Program.cs#L103) (commenting out the version check isn't tenable, there is a genuine problem with loading the Cores assembly):
```
System.IO.FileNotFoundException: Could not load the file 'Bizhawk.Emulation.Cores'.
File name: 'Bizhawk.Emulation.Cores'
  at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef, System.Security.Policy.Evidence assemblySecurity) [0x0007a] in <2b04fb3332af4f9d9f771875ed6702d6>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain.Load(System.Reflection.AssemblyName,System.Security.Policy.Evidence)
  at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef) [0x00000] in <2b04fb3332af4f9d9f771875ed6702d6>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain.Load(System.Reflection.AssemblyName)
  at System.Reflection.Assembly.Load (System.Reflection.AssemblyName assemblyRef) [0x00005] in <2b04fb3332af4f9d9f771875ed6702d6>:0 
  at BizHawk.Client.EmuHawk.Program.SubMain (System.String[] args) [0x0004c] in <4a6164041dd143dcbcc3a2d0e536fb98>:0 
  at BizHawk.Client.EmuHawk.Program.Main (System.String[] args) [0x00001] in <4a6164041dd143dcbcc3a2d0e536fb98>:0 
```

**Comment by InfamousKnight** [comment]
Downloading from appveyor, and the program doesn't run under ubuntu 18.04
sean@sean-HP-Pavilion-Laptop-15-cs0xxx:~$ mono '/home/sean/Downloads/BizHawk_Developer-2019-08-12-105355-#67cbe9a5ee22c8bf83736dc9a2158ecd1032c3a1/EmuHawk.exe' 
 
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'BizHawk.Client.EmuHawk.Program' threw an exception.

**Comment by YoshiRulz** [comment]
@InfamousKnight try master instead, don't forget [deps](https://gitlab.com/TASVideos/BizHawk/snippets/1788335)

**Comment by InfamousKnight** [comment]
What do you mean by master? 

I'm getting the following error:

sean@sean-HP-Pavilion-Laptop-15-cs0xxx:~$ mono '/home/sean/Downloads/BizHawk_Developer-2019-08-12-105355-#67cbe9a5ee22c8bf83736dc9a2158ecd1032c3a1/EmuHawk.exe' 
Gtk-Message: 11:09:38.791: Failed to load module "canberra-gtk-module"

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'BizHawk.Bizware.BizwareGL, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
  at BizHawk.Client.EmuHawk.Program.Main (System.String[] args) [0x00000] in <49db9a6cf2d34904bf96ae4bf875f3b9>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'BizHawk.Bizware.BizwareGL, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
  at BizHawk.Client.EmuHawk.Program.Main (System.String[] args) [0x00000] in <49db9a6cf2d34904bf96ae4bf875f3b9>:0 

when using the appveyor build. I can't seem to find msbuild if building it manually

**Comment by YoshiRulz** [comment]
Sorry, I didn't read the commit in your first message and assumed you downloaded the artifact from this PR. I get the same crash when using that particular build though. You'll have to compile it from source, the same commit (67cbe9a5e) ran as expected when I did that.

MSBuild isn't in the official repos, see [this comment](https://gitlab.com/TASVideos/BizHawk/snippets/1796994#note_191573524) (written for Mint 19 which I believe is the same). You called `mono` from the shell, which should let you load NullHawk, but see `EmuHawkMono.sh`. If you're still having trouble, join IRC.

**Comment by InfamousKnight** [comment]
Downloading the appveyor build on my ubuntu v19.10 64 bit machine and I don't see any EmuHawkMono.sh I also don't know where to get MSbuild so I downloaded the appveyor one.

**Comment by YoshiRulz** [comment]
@InfamousKnight AppVeyor artifacts don't include everything from `output`, we'll add the script to the list eventually. For now you can use [the copy at master](https://raw.githubusercontent.com/TASVideos/BizHawk/master/Assets/EmuHawkMono.sh) (it hasn't changed).

**Comment by InfamousKnight** [comment]
On my end this pops up: 162511-#ae7221988b9552f9d5160f9e960deb0dbc8dd7f2$ '/home/sean/Downloads/BizHawk_Developer-2019-11-02-162511-#ae7221988b9552f9d5160f9e960deb0dbc8dd7f2/EmuHawkMono.sh' 
Gtk-Message: 15:27:17.513: Failed to load module "canberra-gtk-module"

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'BizHawk.Bizware.BizwareGL, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'BizHawk.Bizware.BizwareGL, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
  at BizHawk.Client.EmuHawk.Program.Main (System.String[] args) [0x00000] in <0484e23ceab34542bc1b035b7ca281ff>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'BizHawk.Bizware.BizwareGL, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'BizHawk.Bizware.BizwareGL, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
  at BizHawk.Client.EmuHawk.Program.Main (System.String[] args) [0x00000] in <0484e23ceab34542bc1b035b7ca281ff>:0 

installed mono-devel

**Pull request merged**
