### PR TITLE
[N64] Update RSP-HLE plugin to latest version.

### PR DESCRIPTION
**Pull request by bsmiles32**
This PR updates RSP-HLE plugin to latest version upstream.

Major updates includes:
- better ucodes support (musyx, jpeg, audio, re2, ...)
- possibility to have another RSP plugin as a fallback for tasks that are not yet implemented. This is particularly usefull in conjunction with a LLE RSP plugin such as RSP-CXD4. So you get the best of both world

Upstream switched to msvc 2013, so I added that as well. But I also updated msvc8 and msvc11 project files accordingly.

I don't know very well the BizHawk ecosystem, so please report errors that I've missed while porting this over. For now I've only ported the RSP-HLE plugin because it's simple, I know it very well, and updating it will improves user experience quite a bit. If time allows, I'd like to have BizHawk on par with upstream : I want more N64 TAS !

### CODE REVIEW

**Comment by nattthebear** [comment]
Could you check in the build result?  Presumably `output/dll/mupen64plus-rsp-hle.dll` ?

**Comment by bsmiles32** [comment]
I only have a linux machine available, so can't get/test the dll :( Sorry.

**Comment by bsmiles32** [comment]
Currently downloading the appveyor artifacts, so I might get access to the generated dll.

**Comment by vadosnaprimer** [comment]
I think the new build is exactly what's lacking in it. The bot only rebuilds bizhawk itself.

**Comment by nattthebear** [comment]
Yea, appveyor only builds the main bizhawk solution.  A lot of the other stuff is checked in, for better or worse

**Comment by bsmiles32** [comment]
@nattthebear @vadosnaprimer : gave you write access to my branch if you want so you can update this PR with the build dll.

**Comment by vadosnaprimer** [comment]
Will only be able to help tomorrow, I bet natt beats me to it.

**Comment by NarryG** [comment]
I have an environment set up to build the mupen core as I've previously needed to debug an exception I was experiencing with my project hooking into the core. I can test it in a few hours when I get home if no one else has gotten around to it.

**Comment by NarryG** [comment]
Turns out I don't have the 2013 tools installed. Upgrading to 2017 it compiles fine. If someone with the 2013 tools wants to check that'd be good.

```1>------ Build started: Project: mupen64plus-rsp-hle, Configuration: Release x64 ------
1>alist.c
1>alist_audio.c
1>alist_naudio.c
1>alist_nead.c
1>audio.c
1>cicx105.c
1>hle.c
1>jpeg.c
1>memory.c
1>mp3.c
1>musyx.c
1>c:\daniel\git\bizhawk2\libmupen64plus\mupen64plus-rsp-hle\src\musyx.c(733): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
1>osal_dynamiclib_win32.c
1>plugin.c
1>re2.c
1>   Creating library C:\Daniel\Git\Bizhawk2\libmupen64plus\mupen64plus-rsp-hle\projects\VisualStudio2013\x64\Release\mupen64plus-rsp-hle.lib and object C:\Daniel\Git\Bizhawk2\libmupen64plus\mupen64plus-rsp-hle\projects\VisualStudio2013\x64\Release\mupen64plus-rsp-hle.exp
1>Generating code
1>All 275 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1>Finished generating code
1>mupen64plus-rsp-hle.vcxproj -> C:\Daniel\Git\Bizhawk2\libmupen64plus\mupen64plus-rsp-hle\projects\VisualStudio2013\x64\Release\mupen64plus-rsp-hle.dll
1>Done building project "mupen64plus-rsp-hle.vcxproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by NarryG** [comment]
Here we go. Installed 2013 and it builds fine.
```Build started 6/10/2018 7:47:27 PM.
     1>Project "C:\Daniel\Git\Bizhawk2\libmupen64plus\mupen64plus-rsp-hle\projects\VisualStudio2013\mupen64plus-rsp-hle.vcxproj" on node 2 (Build target(s)).
     1>ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64\CL.exe /c /I"..\..\..\mupen64plus-core\src\api" /Zi /nologo /W3 /WX- /O2 /GL /D WIN32 /D NDEBUG /D _WINDOWS /D _USRDLL /D _CRT_SECURE_NO_DEPRECATE /D inline=__inline /D _WINDLL /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"x64\Release\\" /Fd"x64\Release\vc120.pdb" /Gd /TC /errorReport:prompt ..\..\src\alist.c ..\..\src\alist_audio.c ..\..\src\alist_naudio.c ..\..\src\alist_nead.c ..\..\src\audio.c ..\..\src\cicx105.c ..\..\src\hle.c ..\..\src\jpeg.c ..\..\src\memory.c ..\..\src\mp3.c ..\..\src\musyx.c ..\..\src\osal_dynamiclib_win32.c ..\..\src\plugin.c ..\..\src\re2.c
         alist.c
         alist_audio.c
         alist_naudio.c
         alist_nead.c
         audio.c
         cicx105.c
         hle.c
         jpeg.c
         memory.c
         mp3.c
         musyx.c
     1>..\..\src\musyx.c(733): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
         osal_dynamiclib_win32.c
         plugin.c
         re2.c
       Link:
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:PROMPT /OUT:"C:\Daniel\Git\Bizhawk2\libmupen64plus\mupen64plus-rsp-hle\projects\VisualStudio2013\x64\Release\mupen64plus-rsp-hle.dll" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:\Daniel\Git\Bizhawk2\libmupen64plus\mupen64plus-rsp-hle\projects\VisualStudio2013\x64\Release\mupen64plus-rsp-hle.pdb" /SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF /LTCG /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\Daniel\Git\Bizhawk2\libmupen64plus\mupen64plus-rsp-hle\projects\VisualStudio2013\x64\Release\mupen64plus-rsp-hle.lib" /MACHINE:X64 /DLL x64\Release\alist.obj
         x64\Release\alist_audio.obj
         x64\Release\alist_naudio.obj
         x64\Release\alist_nead.obj
         x64\Release\audio.obj
         x64\Release\cicx105.obj
         x64\Release\hle.obj
         x64\Release\jpeg.obj
         x64\Release\memory.obj
         x64\Release\mp3.obj
         x64\Release\musyx.obj
         x64\Release\osal_dynamiclib_win32.obj
         x64\Release\plugin.obj
         x64\Release\re2.obj
            Creating library C:\Daniel\Git\Bizhawk2\libmupen64plus\mupen64plus-rsp-hle\projects\VisualStudio2013\x64\Release\mupen64plus-rsp-hle.lib and object C:\Daniel\Git\Bizhawk2\libmupen64plus\mupen64plus-rsp-hle\projects\VisualStudio2013\x64\Release\mupen64plus-rsp-hle.exp
         Generating code
         Finished generating code
         mupen64plus-rsp-hle.vcxproj -> C:\Daniel\Git\Bizhawk2\libmupen64plus\mupen64plus-rsp-hle\projects\VisualStudio2013\x64\Release\mupen64plus-rsp-hle.dll
     1>Done Building Project "C:\Daniel\Git\Bizhawk2\libmupen64plus\mupen64plus-rsp-hle\projects\VisualStudio2013\mupen64plus-rsp-hle.vcxproj" (Build target(s)).

Build succeeded.

Time Elapsed 00:00:02.59
```

Here's the output (Release and Debug) [x64.zip](https://github.com/TASVideos/BizHawk/files/2088331/x64.zip)

Mario 64 launches fine.

**Comment by NarryG** [comment]
I've pushed the build as bsmiles32 gave me write access. If one of you wants to build it yourself and replace it, go ahead.

**Comment by nattthebear** [comment]
As the dll is now committed, if merio works fine I see no reason not to merge this

**Comment by NarryG** [comment]
I tested a few games and ran into no visible issues that didn't previously exist due to the core itself being fairly outdated (RE2 still crashes but I'm assuming that's no longer a microcode issue rather an issue with the core being out of date).
I played about 10 minutes of Smash, Mario 64, and OOT and they were all fine.

**Comment by NarryG** [comment]
I've been using it all week and haven't run into any major issues. I'd say it's good to merge unless I missed something.

**Pull request merged**
