### PR TITLE
Fix for #2567 LogKey missing in input log of .bk2 made by importer

### PR DESCRIPTION
**Pull request by YoshiRulz**
#2567

### CODE REVIEW

**Comment by alyosha-tas** [comment]
Do we want the key to come from the emulator? It could be way different then that of the imported file in some cases (like if you have 2 zappers currently plugged in on NES.)

**Comment by YoshiRulz** [comment]
The emulator should be restarted with the correct sync settings when importing a movie. Though I'm not sure if that's the case now.

**Comment by adelikat** [comment]
This isn't the right way to do this.  This causes the import to change the MovieSession state!  Also, does this not put the logkey as the current state of the current emulator? Which isn't guaranteed to be the configuration of the imported movie. I'd rather have no log key than the wrong one.

The importer already has to create a controller object in order to import key presses, it should use that controller state to generate a log key.

**Comment by YoshiRulz** [comment]
I have no idea then. The code which serialises the `LogKey` reads `MovieSession.MovieController` which, without this change, can only ever be set by `MovieSession.RunQueuedMovie`, which in turn is only ever called in `MainForm.StartNewMovie`. (This latter method *can* be called when using the importer, but not with `File` > `Movie` > `Import Movies...`, and I think it's executed in the wrong order for this purpose.)

**Pull request closed without merging**
